### ISSUE TITLE
Change UI.png and Descriptions in DeveloperGuide

### ISSUE THREAD

**Issue by josephambe** [CS2103-AY1819S1-T13-4/main#120]
Updating the current UI.png diagram and adding more thorough descriptions of the UI process in the Developer Guide.

**Comment by jeremiah-ang** [comment]
Do you need help with this?

**Comment by josephambe** [comment]
I just updated it now (see pull request #122 ) but it seemed way to simple...if you have anything to add, please let me know or go for it!
