### ISSUE TITLE
Editing Grade of an incomplete module

### ISSUE THREAD

**Issue by jeremiah-ang** [CS2103-AY1819S1-T13-4/main#147]
Should we allow users to change the grade for incomplete module. 

Might screw up the adjusted grade.

**Comment by jeremiah-ang** [comment]
As long as the grade state is updated accordingly it will not affect the adjusted values. 

i.e. 
```
add cs1234... // cs1234's grade state = incomplete
goal 4.0 // cs1234's grade state = target
adjust cs1234... // cs1234's grade state = adjust
edit cs1234... // cs1234's grade state = complete
```

**Comment by alexkmj** [comment]
I think that we should only allow adjust to change the grade of modules not completed. If  both `adjust` and `edit` are allowed to change grade of module, user might assume that both does the same thing. If we don't allow `edit` to change modules not completed, exception will be thrown and users can at least read and understand that they can't do that. If we allow them to use `edit` to change modules not completed and move it to completed, users may raise this as an issue.

```
add cs1234... // cs1234's grade state = incomplete
goal 4.0 // cs1234's grade state = target
edit cs1234... // throw command exception and inform users to use adjust
```

**Comment by jeremiah-ang** [comment]
Lets make separate issue 1 for edit and 1 for adjust
