### ISSUE TITLE
getOnlyOneModule to throw exception if no module or more than one module found

### ISSUE THREAD

**Issue by alexkmj** [CS2103-AY1819S1-T13-4/main#205]

**Comment by jeremiah-ang** [comment]
I think can drop the `Unique` word. Every module is Unique and the method is expected to return a single Module object.

**Comment by alexkmj** [comment]
> I think can drop the `Unique` word. Every module is Unique and the method is expected to return a single Module object.

I think the name i used wasn't good enough. Changed it to `getOnlyOneModule`. My intention was to let the user of the code know that this method should only get one and only one module just by the name itself.

**Comment by jeremiah-ang** [comment]
You're aware that there already is a method findModule that returns Only One Module by code right?

**Comment by alexkmj** [comment]
> You're aware that there already is a method findModule that returns Only One Module by code right?

Yes. I will update it. I think that the name can be more meaningful since now it throws exception when its not one and only one matches.
